### ISSUE TITLE
Add support for Avro

### ISSUE THREAD

**Issue by akdu12** [spring-cloud-stream-app-starters/mongodb#8]
can we add support for reading Avro data using a Schema Registry Client?

**Comment by artembilan** [comment]
Unfortunately, I'm not sure what you are asking exactly in this project.

The point is that there is already Schema Registry Client support in Spring Cloud Stream on the binder level: http://cloud.spring.io/spring-cloud-static/spring-cloud-stream/2.1.0.RC4/multi/multi_schema-evolution.html

Doesn't sound that there should be anything done from the particular App Starter implementation, which, essentially, binder-agnostic. And there is no any particular data type biasing.

So, please, elaborate more on your concern here or close this issue in favor of existing functionality on the other level.
